### ISSUE TITLE
Equality check in 'Or' pattern

### ISSUE THREAD

**Issue by ilmirons** [k-tsj/pattern-match#4]
Hi, and thank you for porting Pattern matching to Ruby. I'm a novice in this language and I was trying to make a triangle-check function with Pattern matching, but I can't get a working 'isosceles triangle' pattern checking two equal items from an array of three. Is this a limit of the library or I'm getting something wrong? Below is my code
```ruby
def triangle(*args)

  raise TriangleError if args.length != 3

  match(args) do 
  	# [...] some code omitted
  	with(_[a, a, a]) do
  		:equilateral
  	end

  	with(Or(_[a, a, _], _[_, b, b], _[c, _, c])) do
  		:isosceles
	end

	with(_[_, _, _]) do
		:scalene
	end

  end
end
```

**Comment by k-tsj** [comment]
I'm going to close this. Please reopen if you need.
