### ISSUE TITLE
Nested matching in hashes.

### ISSUE THREAD

**Issue by cvb** [k-tsj/pattern-match#6]
Hi, this code raises `NoMatchingPatternError`

```
match({a: :b}) do
  with(Hash.(a: _(n & Symbol))) { n }
end
```
which, I believe, should be equal to `with(Hash.(:a), guard { a.is_a? Symbol }) { a }`

Is it not supported, or maybe I'm doing it wrong?

**Comment by k-tsj** [comment]
Try following code.

~~~ruby
match({a: :b}) do
  with(Hash.(a: n & Symbol)) { n }
end
~~~

`_()` is just for Value patterns, not for And patterns, etc.
(Generally, it's very few that `_()` is needed.)

For example, following code also raises `NoMatchingPatternError`.

~~~ruby
match(:b) do
  with(_(n & Symbol)) { n }
end
~~~

**Comment by cvb** [comment]
Great, it works, thanks.
